server:
    port: 8082
spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: zicai
        password: 12345678
        url: jdbc:mysql://localhost:3306/seckill?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    redis:
        host: localhost
        port: 6379
        database: 0

rocketmq:
    name-server: localhost:9876
    consumer:
        access-key: rocketmq2
        secret-key: 12345678
mybatis:
    mapper-locations: classpath:mapper/*.xml
    configuration:
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl